maximum_name_email: 50
minimum: 6
per_page: 10
limit_book: 5
max_rate: 5
size_image_book: 140
max_length_inline_description: 150
remember_one: 1
limit_length: 150
minimum_rate: 1
size_image_avatar: 100
status_respone: "OK"
